#!/bin/sh
# Run after `hugo -s site`; exits non-zero on the first missing property of the built site.
# The minifier drops attribute quotes, so hrefs are matched with an optional quote.
set -eu
P="$(cd "$(dirname "$0")" && pwd)/public"
check() { name=$1; shift; if "$@" >/dev/null 2>&1; then echo "ok   $name"; else echo "FAIL $name"; exit 1; fi; }
check pages        test -f "$P/spec/06-operators/index.html" -a -f "$P/compat/known-gaps/index.html" -a -f "$P/compat/matrix/index.html" -a -f "$P/adr/0024-ipmatch-invalid-entries/index.html" -a -f "$P/adr/index.html"
check title        grep -q '<title>06. Operators' "$P/spec/06-operators/index.html"
check anchor       grep -qE 'href="?[^" >]*/spec/03-processing-model/#chains' "$P/spec/08-actions/index.html"
check adr-index    grep -q '<title>Architecture Decision Records' "$P/adr/index.html"
check adr-rows     grep -qE 'href="?[^" >]*/adr/0023-reference-adapters/' "$P/adr/index.html"
check adr-no-stray test ! -e "$P/adr/_index"
check spec-order   sh -c "grep -oE 'href=\"?[^\" >]*/spec/[0-9]{2}-[a-z-]+/' '$P/spec/index.html' | head -1 | grep -q 00-conventions"
check adr-ref      grep -qE 'href="?[^" >]*/adr/0002-case-insensitive-names/' "$P/compat/known-gaps/index.html"
check test-ref     grep -qE 'href="?https://github.com/fzipi/seclang-spec/blob/main/tests/engine/actions/setvar.yaml' "$P/compat/known-gaps/index.html"
check dir-ref      sh -c "grep -rhoE 'href=\"?https://github.com/fzipi/seclang-spec/(blob|tree)/main/[^\" >]*' '$P/spec' '$P/adr' '$P/compat' | grep -q 'tree/main/adapters/coraza' && ! grep -rhoE 'href=\"?https://github.com/fzipi/seclang-spec/blob/main/[^\" >]*' '$P/spec' '$P/adr' '$P/compat' | grep -vE '\\.[A-Za-z0-9_.-]+$' | grep -q ."
check template     test ! -e "$P/adr/0000-template"
check coraza-adr   sh -c "grep -q 'corazawaf/coraza/tree/main/docs/adr' '$P/adr/0008-collection-key-case/index.html' && ! grep -oE '<p>.*</p>' '$P/adr/0008-collection-key-case/index.html' | grep -q '/adr/0015-mandatory-rule-id/'"
check gaps-table   grep -q '<th>Behaviour today</th>' "$P/compat/known-gaps/index.html"
check no-md-links  sh -c "! (grep -rhoE 'href=\"?[^\" >]*\.md([#\" >]|$)' '$P/spec' '$P/adr' '$P/compat' | grep -v 'https://github.com/' | grep -q .)"
check adr-table    sh -c "grep -oE '<td[^>]*><a href=\"?[^\" >]*' '$P/adr/index.html' | grep -q '/adr/0023-reference-adapters/'"
check formal       test -f "$P/formal/index.html" -a -f "$P/formal/results/index.html"
check formal-title grep -q '<title>Formal model results' "$P/formal/results/index.html"
check formal-table grep -q '<th>Theorem</th>' "$P/formal/results/index.html"
check formal-ref   grep -qE 'href="?https://github.com/fzipi/seclang-spec/tree/main/tests/unit/operators' "$P/formal/results/index.html"
check formal-menu  grep -qE 'href="?[^" >]*/formal/' "$P/spec/index.html"
check home         grep -q "Known gaps" "$P/index.html"
check home-cards   grep -qE '<a[^>]*hextra-card[^>]*href="?[^" >]*compat/known-gaps' "$P/index.html"
check home-formal  grep -qE '<a[^>]*hextra-card[^>]*href="?[^" >]*formal/results' "$P/index.html"
check cards-top    sh -c "grep -q 'mt-auto\"]{margin-top:0' \"$P\"/css/compiled/*.css"
check home-tests   grep -qE '<a[^>]*hextra-card[^>]*href="?https://github.com/fzipi/seclang-spec/tree/main/tests' "$P/index.html"
echo "smoke: all checks passed"
