name = "seclang"
defaultTargets = ["seclang-check", "seclang-parse"]

[[lean_lib]]
name = "SecLang"

[[lean_exe]]
name = "seclang-check"
root = "Main"

[[lean_exe]]
name = "seclang-parse"
root = "ParseMain"
